### ISSUE TITLE
0.1.0 checklist

### ISSUE THREAD

**Issue by aravindhebbali** [rsquaredacademy/xplorerr#11]
Prepare for release:

* [ ] Check that description is informative
* [ ] Check licensing of included files
* [ ] `devtools::check_win_devel()`
* [ ] `rhub::check_for_cran()`

Perform release:

* [ ] Bump version (in DESCRIPTION and NEWS)
* [ ] Update NEWS
* [ ] Update CRAN comments
* [ ] Check package version in zzz.R
* [ ] `devtools::check_win_devel()` (again!)
* [ ] `devtools::submit_cran()`
* [ ] `pkgdown::build_site()`
* [ ] Approve email

Wait for CRAN...

* [ ] Tag release
* [ ] Bump dev version
* [ ] Write blog post
* [ ] Tweet
* [ ] Add link to blog post in pkgdown news menu

Template from <https://github.com/r-lib/usethis/issues/338>
